# Generated by Django 2.2.16 on 2022-07-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
