# Generated by Django 2.2.16 on 2022-08-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20220806_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст поста', max_length=500, verbose_name='Текст поста'),
        ),
    ]
